import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { prisma } from './test-db.mjs';
import * as registry from './project-registry-store.ts';
import * as board from './board-store.ts';
import { listFlowProjectNames } from './flows-store.ts';
const owner = { id: 'visibility-owner', role: 'OWNER', memberships: [] };
const admin = { ...owner, id: 'visibility-admin', role: 'ADMIN' };
const created = [];
after(async () => {
  await prisma.completion.deleteMany({ where: { projectSlug: { in: created } } });
  await prisma.issue.deleteMany({ where: { projectSlug: { in: created } } });
  await prisma.projectRepository.deleteMany({ where: { projectSlug: { in: created } } });
  await prisma.flowProject.deleteMany({ where: { slug: { in: created } } });
  await prisma.accessAudit.deleteMany({ where: { actorId: { in: [owner.id, admin.id] } } });
  await prisma.$disconnect();
});
test('표시 여부는 버전과 권한을 검사해 저장하고 기존 이슈·오늘·완료·저장소를 보존한다', async () => {
  assert.equal(typeof registry.setProjectTaskVisibility, 'function');
  const input = { title: '표시 테스트', scope: 'PERSONAL', personalGroup: 'TOY', repositories: [{ workspace: 'UK', path: 'visibility-test' }] };
  const project = await registry.saveManagedProject(owner, input); created.push(project.slug);
  assert.equal(project.showInTasks, true);
  const now = new Date().toISOString();
  await board.createIssue({ id: 'visibility-pool', projectSlug: project.slug, title: '남길 이슈', now });
  await board.createIssue({ id: 'visibility-today', projectSlug: project.slug, title: '오늘', now });
  await board.moveIssue('visibility-today', 'today', '2026-09-22');
  await board.setIssueDone({ id: 'visibility-today', done: true, completionId: 'visibility-done', today: '2026-09-22', now });
  const issues = await prisma.issue.findMany({ where: { projectSlug: project.slug }, orderBy: { id: 'asc' } });
  const completions = await prisma.completion.findMany({ where: { projectSlug: project.slug } });
  for (const actor of [admin, { ...owner, role: 'MEMBER' }]) await assert.rejects(() => registry.setProjectTaskVisibility(actor, project.slug, false, project.revision), error => error.status === 403);
  await assert.rejects(() => registry.setProjectTaskVisibility(owner, project.slug, 'false', project.revision));
  const hidden = await registry.setProjectTaskVisibility(owner, project.slug, false, project.revision);
  assert.equal(hidden.showInTasks, false);
  assert.deepEqual(hidden.repositories.map(({ workspace, path }) => ({ workspace, path })), input.repositories);
  assert.equal((await registry.listManagedProjects(owner, 'PERSONAL')).find(row => row.slug === project.slug).showInTasks, false);
  assert.equal((await listFlowProjectNames()).find(row => row.slug === project.slug).showInTasks, false);
  await assert.rejects(() => registry.setProjectTaskVisibility(owner, project.slug, true, project.revision), error => error.status === 409);
  await assert.rejects(() => board.createIssue({ id: 'visibility-blocked', projectSlug: project.slug, title: '신규', now }), error => error.status === 409);
  const renamed = await registry.saveManagedProject(owner, { ...input, title: '이름 변경', revision: hidden.revision }, project.slug);
  assert.equal(renamed.showInTasks, false);
  const outcomes = await Promise.allSettled([true, false].map(flag => registry.setProjectTaskVisibility(owner, project.slug, flag, renamed.revision)));
  assert.equal(outcomes.filter(row => row.status === 'fulfilled').length, 1);
  const latest = outcomes.find(row => row.status === 'fulfilled').value;
  const restored = await registry.setProjectTaskVisibility(owner, project.slug, true, latest.revision);
  assert.equal(restored.showInTasks, true);
  assert.deepEqual(await prisma.issue.findMany({ where: { projectSlug: project.slug }, orderBy: { id: 'asc' } }), issues);
  assert.deepEqual(await prisma.completion.findMany({ where: { projectSlug: project.slug } }), completions);
  await board.createIssue({ id: 'visibility-restored', projectSlug: project.slug, title: '추가 가능', now });
  const company = await registry.saveManagedProject(admin, { title: '회사', scope: 'COMPANY', repositories: [], showInTasks: false }); created.push(company.slug);
  assert.equal(company.showInTasks, false);
  assert.equal((await registry.setProjectTaskVisibility(admin, company.slug, true, company.revision)).showInTasks, true);
});
