import assert from 'node:assert/strict';
import { after, test } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, writeFile, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { prisma } from './test-db.mjs';
import { publicPortfolioKey } from '../public-portfolio.ts';

const directory = await mkdtemp(join(tmpdir(), 'public-portfolio-import-'));
const inputPath = join(directory, 'input.json');
const backupPath = join(directory, 'backup.json');
const run = (...args) => promisify(execFile)(process.execPath, ['--experimental-strip-types', 'scripts/import-public-portfolio.mjs', ...args], { env: { ...process.env, DATABASE_URL: process.env.TEST_DATABASE_URL } });
after(async () => { await prisma.appSetting.deleteMany({ where: { key: publicPortfolioKey } }); await prisma.$disconnect(); await rm(directory, { recursive: true, force: true }); });
test('초기 등록은 읽기 전용 검토·해시·백업·재조회를 거치고 변경된 DB 상태는 거절한다', async () => {
  await prisma.appSetting.deleteMany({ where: { key: publicPortfolioKey } });
  const portfolio = { published: true, content: { name: '테스트', headline: '개발자', introduction: ['소개'], links: [], strengths: [], skills: [], projects: [], activities: [] } };
  await writeFile(inputPath, JSON.stringify({ expectedRevision: 0, portfolio }));
  const inspect = JSON.parse((await run('inspect', inputPath)).stdout);
  assert.equal(await prisma.appSetting.count({ where: { key: publicPortfolioKey } }), 0);
  await assert.rejects(() => run('apply', inputPath, 'wrong', backupPath));
  await assert.rejects(() => stat(backupPath), error => error.code === 'ENOENT');
  const result = await run('apply', inputPath, inspect.sha256, backupPath);
  assert.equal(JSON.parse(result.stdout.trim().split('\n').at(-1)).verified, true);
  assert.equal(JSON.parse(await readFile(backupPath, 'utf8')).row, null);
  assert.equal((await stat(backupPath)).mode & 0o777, 0o600);
  const before = await prisma.appSetting.findUnique({ where: { key: publicPortfolioKey } });
  assert.equal(before.value.revision, 1);
  await assert.rejects(() => run('apply', inputPath, inspect.sha256, join(directory, 'repeat.json')));
  await writeFile(inputPath, JSON.stringify({ expectedRevision: 1, portfolio: { ...portfolio, published: false } }));
  const updateInspect = JSON.parse((await run('inspect', inputPath)).stdout);
  await prisma.appSetting.update({ where: { key: publicPortfolioKey }, data: { value: { ...before.value, content: { ...portfolio.content, name: '다른 수정' } } } });
  await assert.rejects(() => run('apply', inputPath, updateInspect.sha256, join(directory, 'stale.json')));
  assert.equal((await prisma.appSetting.findUnique({ where: { key: publicPortfolioKey } })).value.content.name, '다른 수정');
  const latest = JSON.parse((await run('inspect', inputPath)).stdout);
  await run('apply', inputPath, latest.sha256, join(directory, 'update-backup.json'));
  const saved = await prisma.appSetting.findUnique({ where: { key: publicPortfolioKey } });
  assert.equal(saved.value.revision, 2);
  assert.equal(saved.value.published, false);
});
