import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { prisma } from './test-db.mjs';
import { credentialsKey } from '../recruitment-credentials.ts';

const id = 'test-credentials-import';
const key = `recruitment:document:${id}`;
const directory = await mkdtemp(join(tmpdir(), 'credentials-import-'));
const inputPath = join(directory, 'input.json');
const backupPath = join(directory, 'backup.json');
const run = (...args) => promisify(execFile)(process.execPath, ['--experimental-strip-types', 'scripts/import-recruitment-credentials.mjs', ...args], { env: { ...process.env, DATABASE_URL: process.env.TEST_DATABASE_URL } });
after(async () => { await prisma.appSetting.deleteMany({ where: { key: { in: [key, credentialsKey] } } }); await prisma.$disconnect(); await rm(directory, { recursive: true, force: true }); });
test('지원용 정보 분리는 검토·백업 후 원자적으로 적용하고 재실행·버전 불일치를 거절한다', async () => {
  await prisma.appSetting.deleteMany({ where: { key: { in: [key, credentialsKey] } } });
  const document = { id, kind: 'PORTFOLIO', title: '테스트 포트폴리오', project: '', scope: 'PERSONAL', summary: '', tags: [], sourceUrls: [], sections: [{ title: '자격', body: '2025-09 테스트 자격' }], revision: 1, updatedAt: new Date().toISOString() };
  await prisma.appSetting.create({ data: { key, value: document } });
  const input = { documentId: id, expectedRevision: 1, items: [{ id: 'certificate', kind: 'CERTIFICATE', name: '테스트 자격', issuer: '', acquiredOn: '2025-09', identifier: '', grade: '', expiresOn: '', notes: '' }], replacements: [{ sectionTitle: '자격', from: '2025-09 ', to: '', count: 1 }] };
  const bytes = JSON.stringify(input);
  const sha = createHash('sha256').update(bytes).digest('hex');
  await writeFile(inputPath, bytes);
  await run('inspect', inputPath);
  assert.equal(await prisma.appSetting.count({ where: { key: credentialsKey } }), 0);
  await assert.rejects(() => run('apply', inputPath, 'wrong', backupPath));
  await prisma.appSetting.update({ where: { key }, data: { value: { ...document, revision: 2 } } });
  await assert.rejects(() => run('apply', inputPath, sha, backupPath));
  assert.equal(await prisma.appSetting.count({ where: { key: credentialsKey } }), 0);
  await prisma.appSetting.update({ where: { key }, data: { value: document } });
  await run('apply', inputPath, sha, backupPath);
  const saved = await prisma.appSetting.findUnique({ where: { key } });
  assert.equal(saved.value.sections[0].body, '테스트 자격');
  assert.equal(saved.value.revision, 2);
  assert.equal((await prisma.appSetting.findUnique({ where: { key: credentialsKey } })).value.items[0].acquiredOn, '2025-09');
  assert.deepEqual(JSON.parse(await readFile(backupPath, 'utf8')).rows[0].value, document);
  await assert.rejects(() => run('apply', inputPath, sha, join(directory, 'repeat.json')));
  assert.deepEqual(await prisma.appSetting.findUnique({ where: { key } }), saved);
});
