import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { prisma } from './test-db.mjs';

const id = 'test-recruitment-import';
const key = `recruitment:document:${id}`;
const directory = await mkdtemp(join(tmpdir(), 'recruitment-test-'));
const input = join(directory, 'input.json');
const backup = join(directory, 'backup.json');
const run = (...args) => promisify(execFile)(process.execPath, ['--experimental-strip-types', 'scripts/import-recruitment.mjs', ...args], { env: { ...process.env, DATABASE_URL: process.env.TEST_DATABASE_URL } });
after(async () => { await prisma.appSetting.deleteMany({ where: { key } }); await prisma.$disconnect(); await rm(directory, { recursive: true, force: true }); });
test('자료 등록은 검토 해시와 백업을 요구하고 재실행·편집 충돌에서 기존 문서를 보존한다', async () => {
  await prisma.appSetting.deleteMany({ where: { key } });
  const document = { id, kind: 'EXPERIENCE', title: '이관 검증', project: '테스트', scope: 'PERSONAL', summary: '', sections: [{ title: '근거', body: 'source' }], tags: [], sourceUrls: [] };
  const bytes = JSON.stringify([document]);
  await writeFile(input, bytes);
  const sha = createHash('sha256').update(bytes).digest('hex');
  const inspect = JSON.parse((await run('inspect', input)).stdout.trim());
  assert.equal(inspect.new, 1);
  assert.equal(await prisma.appSetting.count({ where: { key } }), 0);
  await assert.rejects(() => run('apply', input, 'wrong-hash', backup));
  assert.equal(await prisma.appSetting.count({ where: { key } }), 0);
  await run('apply', input, sha, backup);
  const saved = await prisma.appSetting.findUnique({ where: { key } });
  assert.equal(saved.value.revision, 1);
  assert.deepEqual(JSON.parse(await readFile(backup, 'utf8')).rows, []);
  await run('apply', input, sha, join(directory, 'repeat.json'));
  assert.deepEqual(await prisma.appSetting.findUnique({ where: { key } }), saved);
  await prisma.appSetting.update({ where: { key }, data: { value: { ...saved.value, title: '화면에서 수정', revision: 2 } } });
  await assert.rejects(() => run('apply', input, sha, join(directory, 'conflict.json')));
  assert.equal((await prisma.appSetting.findUnique({ where: { key } })).value.title, '화면에서 수정');
});
